org: mmanna3
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x  	
  # httpApi:
  #   cors: true


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
